#!/bin/bash

# Variaveis.
HOSTNAME="MongoDB-shard"
IMAGE="centos:mongodb"
IP="192.168.10.61"
PORTA="27011"
SSH="2220"
DirLogH="/storage/mongo/shard-log"
DirLogC="/var/log/mongo"
DirMongoH="/storage/mongo/shard"
DirMongoC="/mongo/shard"

# Removendo o Container morto.
docker rm -f $(docker ps -aq --filter "name=$HOSTNAME") >> /dev/null 2>&1

# Iniciando o Container novo.
docker run -dP \
--privileged \
-p $IP:$PORTA:$PORTA \
-p $IP:$SSH:22 \
--volume=$DirMongoH:$DirMongoC \
--volume=$DirLogH:$DirLogC \
--name=$HOSTNAME \
$IMAGE

# Recebendo o ID do novo container.
id=$(docker ps -q --filter "name=$HOSTNAME")
echo $id

# docker exec.
docker exec $id export LC_ALL=C
docker exec  $id mongod --bind_ip 0.0.0.0 --port $PORTA  --dbpath $DirMongoC --logpath $DirLogC/$HOSTNAME
